export const ERROR_MESSAGES_ES: Record<number, string> = {
    0:  "Ha ocurrido un error inesperado",
    1:  "El identificador de la madre es obligatorio",
    2:  "El identificador de la cría es obligatorio",
    3:  "La fecha de nacimiento es obligatoria",
    4:  "El sexo es obligatorio",
    5:  "La raza es obligatoria",
    6:  "La aptitud es obligatoria",
    7:  "El tipo de muerte es obligatorio",
    8:  "La fecha de muerte es obligatoria",
    9:  "Los meses de gestación son obligatorios",
    10: "La latitud es obligatoria",
    11: "La longitud es obligatoria",
    12: "El identificador del animal es obligatorio",
    13: "La fecha de identificación es obligatoria",
    14: "El código REMO es obligatorio",
    15: "La fecha de llegada es obligatoria",
    16: "La hora de llegada es obligatoria",
    17: "El código ATES es obligatorio",
    18: "La explotación destino es obligatoria",
    19: "El estado de llegada es obligatorio",
    20: "La explotación origen es obligatoria",
    21: "El tipo de traslado es obligatorio",
    22: "La fecha de salida es obligatoria",
    23: "La hora de salida es obligatoria",
    24: "El tipo de movilidad es obligatorio",
};

export const ERROR_MESSAGES_CA: Record<number, string> = {
    0:  "S'ha produït un error inesperat",
    1:  "L'identificador de la mare és obligatori",
    2:  "L'identificador de la cria és obligatori",
    3:  "La data de naixement és obligatòria",
    4:  "El sexe és obligatori",
    5:  "La raça és obligatòria",
    6:  "L'aptitud és obligatòria",
    7:  "El tipus de mort és obligatori",
    8:  "La data de mort és obligatòria",
    9:  "Els mesos de gestació són obligatoris",
    10: "La latitud és obligatòria",
    11: "La longitud és obligatòria",
    12: "L'identificador de l'animal és obligatori",
    13: "La data d'identificació és obligatòria",
    14: "El codi REMO és obligatori",
    15: "La data d'arribada és obligatòria",
    16: "L'hora d'arribada és obligatòria",
    17: "El codi ATES és obligatori",
    18: "L'explotació destí és obligatòria",
    19: "L'estat d'arribada és obligatori",
    20: "L'explotació origen és obligatòria",
    21: "El tipus de trasllat és obligatori",
    22: "La data de sortida és obligatòria",
    23: "L'hora de sortida és obligatòria",
    24: "El tipus de mobilitat és obligatori",
};

export function getErrorMessage(codigo: number, lang: string): string {
    const messages = lang === "ca" ? ERROR_MESSAGES_CA : ERROR_MESSAGES_ES;
    return messages[codigo] ?? messages[0];
}